### ISSUE TITLE
Won't start on Neovim

### ISSUE THREAD

**Issue by snoblenet** [chemzqm/tern-neovim#1]
Hi there,

I've install tern-neovim on Neovim using Plug and the usual methods. I'm getting this error when I try to enter a JS file:
```
Error detected while processing function tern#Enable:
E117: Unknown function: TernStart
E117: Unknown function: TernStart
```
Any thoughts?

**Comment by iamcco** [comment]
type `:UpdateRemotePlugins` in neovim
