### ISSUE TITLE
E117: Unknown function: TernStart in Neovim (v0.3.0)

### ISSUE THREAD

**Issue by asishallab** [chemzqm/tern-neovim#2]
This is probably identical to Issue #1 .

I am using CentOS 7 and neovim (v0.3.0). My plugin manager is [vim-plug](https://github.com/junegunn/vim-plug) and you can find my neovim-setup [here](https://github.com/asishallab/neovim_config/blob/master/init.vim).

To install tern-neovim I first added it to my vim-plug plugin-list, installed it with `:PlugUpdate`, and then ran `npm install --save .` in the `~/.nvim/plugged/tern-neovim` directory with success.

The important line in my `init.vim` is
```
Plug 'neoclide/tern-neovim', { 'for': 'javascript' }
```
I also tried including tern-neovim always, not only when opening a javascript file
```
Plug 'neoclide/tern-neovim'
```

In both cases, when loading a javascript file I get the error
```
Error detected while processing function tern#Enable:                                                                                           
line    2:                                                                                                                                      
E117: Unknown function: TernStart
```

Manually executing `:UpdateRemotePlugins` does not resolve the issue unfortunately.

Help would be most appreciated.

**Comment by chemzqm** [comment]
Remove `{ 'for': 'javascript' }`, it's useless, function of remote plugin already load on demond.

**Comment by asishallab** [comment]
@chemzqm Thank you for your quick reply.

Unfortunately, it does not work removing the `{ 'for': 'javascript' }`.

As I have indicated in my original description of the problem, the error occurs in both cases, including the plugin with or without the optional `{'for': 'javascript'}`.

Please help. Thank you

**Comment by chemzqm** [comment]
The python remote plugin not registed, try command `:checkhealth`

**Comment by asishallab** [comment]
Dear @chemzqm  thank you for your quick response and efforts. I followed your instructions and indeed the python and node.js packages were missing. However, after installing them the error persists.

`:checkhealth` gives the following output

```

health#nvim#check
========================================================================
## Configuration
  - WARNING: $NVIM_TUI_ENABLE_CURSOR_SHAPE is ignored in Nvim 0.2+
    - ADVICE:
      - Use the 'guicursor' option to configure cursor shape. :help |'guicursor'|
      - https://github.com/neovim/neovim/wiki/Following-HEAD#20170402

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/3'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.5
  - INFO: python2-neovim version: 0.2.6
  - OK: Latest python2-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.4.9
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.11.0
  - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm package is installed: 4.2.1
```

Any clues?

**Comment by chemzqm** [comment]
I think you just need to run `:UpdateRemotePlugins` and make sure the python functions get registed.

Why not try out https://github.com/neoclide/coc.nvim, it has great tsserver support for javascript and typescript.  This plugin and tern itself is not actively maintained.

**Comment by asishallab** [comment]
@chemzqm Thank you very much for offering help on a non maintained plugin! It seems to work now. And even more thanks for mentioning the `coc.nvim` plugin. I will give that a thorough look.
